default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: {{ database_user}}
  password: {{ database_password }}

{{ env }}:
  <<: *default
  database: {{ database_name }}
